### PR TITLE
Support Traditional Chinese 

### PR DESCRIPTION
**Pull request by pewsheen**
I added i18n support and a simple SChinese to TChinese converter if theres update for subtitle.

### CODE REVIEW

**Comment by pewsheen** [comment]
Found a bug, close first.

**Comment by pewsheen** [comment]
lol... I forgot to load TChinese subtitle at start.
It should be fine now.

**Comment by grzhan** [comment]
Thanks @pewsheen ! I will merge this PR later.

**Comment by grzhan** [comment]
@pewsheen ,you can now install [v0.3.0-beta.1](https://github.com/kcwikizh/poi-plugin-subtitle/releases/tag/v0.3.0-beta.1)
If you find any bugs, please report them, thank you! :)

**Comment by pewsheen** [comment]
Sure, thanks!

**Pull request merged**
